services:
  - type: web
    name: ai-testcase-generator
    runtime: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0

    envVars:
      - key: GEMINI_API_KEY
        sync: false
